"""empty message

Revision ID: 120f5ddaf8af
Revises: 
Create Date: 2021-02-20 23:00:43.827459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120f5ddaf8af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
