"""empty message

Revision ID: e892626b49d1
Revises: 3e9380f52076
Create Date: 2021-03-05 18:11:21.126745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e892626b49d1'
down_revision = '3e9380f52076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('_s_pwd', sa.String(length=255), nullable=True))
    op.drop_column('student', 's_pwd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('s_pwd', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('student', '_s_pwd')
    # ### end Alembic commands ###
