"""empty message

Revision ID: 15275b9950fd
Revises: ab5362bcfcb9
Create Date: 2021-04-08 15:37:56.493232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15275b9950fd'
down_revision = 'ab5362bcfcb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('o_user_id', sa.Integer(), nullable=True),
    sa.Column('o_hall_movie_id', sa.Integer(), nullable=True),
    sa.Column('o_time', sa.DateTime(), nullable=True),
    sa.Column('o_status', sa.Integer(), nullable=True),
    sa.Column('o_seats', sa.String(length=128), nullable=True),
    sa.Column('o_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['o_hall_movie_id'], ['hall_movie.id'], ),
    sa.ForeignKeyConstraint(['o_user_id'], ['movie_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('h_num', table_name='hall')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('h_num', 'hall', ['h_num'], unique=True)
    op.drop_table('movie_order')
    # ### end Alembic commands ###
