"""empty message

Revision ID: 46d2a56482fb
Revises: e494bc21614f
Create Date: 2021-03-29 11:44:59.454032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46d2a56482fb'
down_revision = 'e494bc21614f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cp_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cp_name')
    )
    op.create_table('cinema_user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('_password', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.Column('is_verity', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cinema_user_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_user_id', sa.Integer(), nullable=True),
    sa.Column('cp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_user_id'], ['cinema_user.id'], ),
    sa.ForeignKeyConstraint(['cp_id'], ['cinema_permission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_user_permission')
    op.drop_table('cinema_user')
    op.drop_table('cinema_permission')
    # ### end Alembic commands ###
