"""empty message

Revision ID: 603a1b33248f
Revises: 77265817cc9a
Create Date: 2021-03-30 16:27:09.225208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603a1b33248f'
down_revision = '77265817cc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cinema_movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('c_user_id', sa.Integer(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['c_user_id'], ['cinema_user.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cinema_movies')
    # ### end Alembic commands ###
