"""empty message

Revision ID: ab5362bcfcb9
Revises: a214b2761e42
Create Date: 2021-04-01 16:36:20.693238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5362bcfcb9'
down_revision = 'a214b2761e42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall_movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('h_movie_id', sa.Integer(), nullable=True),
    sa.Column('h_hall_id', sa.Integer(), nullable=True),
    sa.Column('h_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['h_hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['h_movie_id'], ['movies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_movie')
    # ### end Alembic commands ###
